### ISSUE TITLE
Firefox doesn’t work

### ISSUE THREAD

**Issue by dgrammatiko** [vikaskbh/exitsplash#1]
I don’t get the widow in firefox. I am on 32.0.3

**Comment by vikaskbh** [comment]
line 36 -> if (/Firefox[\/\s](d+)/.test(navigator.userAgent) && new Number(RegExp.$1) >= 4) {

should be... 

if (/Firefox[\/\s](d+)/.test(navigator.userAgent) && new Number(RegExp.$1) >= 4 && new Number(RegExp.$1) < 32) {

updating it.

**Comment by shallumvohr** [comment]
alert message not appearing in firefox!!

**Comment by vikaskbh** [comment]
Upgrade jquery to latest version http://code.jquery.com/jquery-2.2.0.min.js

**Comment by shallumvohr** [comment]
i have updated this still not working, here is the page:https://pagedesigner.pk/exitsplash-master/demo.html
