### ISSUE TITLE
Alert message not working in firefox

### ISSUE THREAD

**Issue by shallumvohr** [vikaskbh/exitsplash#2]
i have observed that the alert message is not appearing in firefox latest version to date, it shows following message alert in popup dialogue **"This page is asking you to confirm that you want to leave - data you have entered may not be saved."** sometime this alert not appear at all.

**Comment by vikaskbh** [comment]
http://stackoverflow.com/a/9420213

**Comment by shallumvohr** [comment]
is thr any alternative to window.onbeforeunload?
