### ISSUE TITLE
Page is blocked when HREF is clicked

### ISSUE THREAD

**Issue by dipen10** [vikaskbh/exitsplash#3]
Hi Vikas

Thanks for your script. 

I have tried your script and its working fine. But today its trigger the page block when i click the HREF link in all browsers ( latest version)

Could you please help me?

**Comment by vikaskbh** [comment]
no. its out dated repository. try finding other hacks. all mobile browser stop supporting onbeforeunload & desktop will also.

**Comment by dipen10** [comment]
I have searched but unable to find anything bro.

Do you know anything. that would be great help bro.

Please help me. thanks bro.

*RegardsDipen Baskaran*
